apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dotbench 
  labels:
    app: dotbench 
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: dotbench
    spec:
      containers:
      - name: dotbench
        image: gcr.io/k8s-hybrid-cloud-demo/dotproduct:1.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "100Mi"
            cpu: "1"
      nodeSelector:
        node.alpha.kubernetes-incubator.io/nfd-cpuid-AVX512BW: "true"
        node.alpha.kubernetes-incubator.io/nfd-cpuid-AVX512CD: "true"
        node.alpha.kubernetes-incubator.io/nfd-cpuid-AVX512DQ: "true"
        node.alpha.kubernetes-incubator.io/nfd-cpuid-AVX512F: "true"
        node.alpha.kubernetes-incubator.io/nfd-cpuid-AVX512VL: "true"
#      restartPolicy: Never
