apiVersion: batch/v1
kind: Job 
metadata:
  name: dotproduct 
  labels:
    app: dotproduct 
spec:
  template:
    metadata:
      labels:
        app: dotproduct
    spec:
      containers:
      - name: dotproduct
        image: gcr.io/k8s-hybrid-cloud-demo/dotproduct:1.0
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do /app/dotproduct; echo 'done'; done;" ]
        imagePullPolicy: Always
        resources:
          limits:
            memory: "100Mi"
            cpu: "1"
      restartPolicy: Never
      nodeSelector:
        node.alpha.kubernetes-incubator.io/nfd-cpuid-AVX512BW: "true"
        node.alpha.kubernetes-incubator.io/nfd-cpuid-AVX512CD: "true"
        node.alpha.kubernetes-incubator.io/nfd-cpuid-AVX512DQ: "true"
        node.alpha.kubernetes-incubator.io/nfd-cpuid-AVX512F: "true"
        node.alpha.kubernetes-incubator.io/nfd-cpuid-AVX512VL: "true"

