apiVersion: extensions/v1beta1
kind: ReplicaSet 
metadata:
  name: dotproduct
  annotations:
    federation.kubernetes.io/replica-set-preferences: |
        {
            "rebalance": true,
            "clusters":  {
              "gke": {
                "weight": 100
              }
            }
        }
  labels:
    app: dotproduct 
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: dotproduct 
    spec:
      containers:
      - name: dotbench
        image: gcr.io/k8s-hybrid-cloud-demo/dotproduct:1.0
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do /app/dotproduct; done;" ]
        imagePullPolicy: Always
        resources:
          limits:
            memory: "100Mi"
            cpu: "1"
      nodeSelector:
        node.alpha.kubernetes-incubator.io/nfd-cpuid-AVX512BW: "true"
        node.alpha.kubernetes-incubator.io/nfd-cpuid-AVX512CD: "true"
        node.alpha.kubernetes-incubator.io/nfd-cpuid-AVX512DQ: "true"
        node.alpha.kubernetes-incubator.io/nfd-cpuid-AVX512F: "true"
        node.alpha.kubernetes-incubator.io/nfd-cpuid-AVX512VL: "true"
#      restartPolicy: Never
